apiVersion: v2
name: mastodata
description: A Helm chart to automate installation and configuration of dependencies
type: application
version: "0.1.0"
appVersion: "0.1.0"
dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"

  - name: cert-manager
    version: "v1.13.0"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled

  - name: questdb
    version: "0.33.0"
    repository: "https://helm.questdb.io/"
