secrets:
    ghcrlogin:
        data: ENC[AES256_GCM,data:tTHHm9y2866qIIFJvxMk6fPKTDdQjpIliXwpbfDb0DJzKGs8IYRWPVQDN60GluJ7uUlvAlMEbhcojAw3WSdhXqeua65XUSVckSagG58tVT6H0WwiZsSSJNEJnNFhpjUlu3GiMYle2k1YMW80t9Qf13O0p2eby5xzDeuFf8fL7qW/z/rWhS6KhTLPx67XxJf7qo4kIjoD32WnGR6SDoSRoodOIipMp996FGzlfw==,iv:jO0bCSjhNsSn7SV1545+r77Oc7n1pYaKkS+Uq5yZ1xU=,tag:un3z7L+YcAZUnFLUfXwmGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e625734tkl6e2rteylqhkpzl74j9gqwxx0pfpj32f26dehpa5y6ssuzdcl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN2x6MlIxdFdFSVZjVWFC
            enJldXBTSGx6bDNSYSsvZHhHTmIyN1Q3ckg4Ck5MSEZSVmU0bmlDYWZmdU5kVHRY
            UW56dFlaTDhNNDE3c1FGci8vVHF1Uk0KLS0tIFJOekdtV0FFcElyMG9ydDl3R2pa
            VlpqT0d6N2pIMUFSK29LNys2WUFMcUUKqoNESN00Vu2vH8fqCoGOrwGfXtgMlGR+
            QjCKU2o3WWaWZbCjKkZIPK0rVQBu9FQEgAWKR1HcYGLwLvQe0Z2BKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-09T16:55:31Z"
    mac: ENC[AES256_GCM,data:mhUV7HnIhYHjDzf+b8hkkCjPevatxdphG6N4iuGytR/wMpZ5EMe3JoXa4l0mh3IeJSPYw/yl/Ada+KN49OFgkKEMtRoG+DRfXyOGQWbbkemKZs6H2dduIz4vlEapCRsocVxdI6rr8L5nYJsHHjbD3Mz3mdNj5I7DScd7eTWGMtI=,iv:SKb8OjfExJxXFZUmh5uZbbViK59YLCD5rWZSX8o0Io0=,tag:MFLjc5aekJPrCFtGckSufQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
